name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-lib:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: ./.github/actions/node-setup

      - name: Build
        run: npm run build:lib

  build-playground:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: ./.github/actions/node-setup

      - name: Build playground
        run: npm run build

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: ./.github/actions/node-setup

      - name: Run tests
        run: npm run ci:test

    lint:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3

        - name: Setup node
          uses: ./.github/actions/node-setup

        - name: Run tests
          run: npm run ci:lint
